<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    use HasFactory;

    public $timestamps = false;
    public $fillable = [
        'name',
        'slug',
        'date'
    ];

    public function registrations()
    {
        return $this->hasManyThrough(Registration::class, EventTicket::class, 'event_id', 'ticket_id');
    }

    public function tickets()
    {
        return $this->hasMany(EventTicket::class, 'event_id', 'id');
    }

    public function channels()
    {
        return $this->hasMany(Channel::class, 'event_id', 'id');
    }

    public function organizer()
    {
        return $this->belongsTo(Organizer::class, 'organizer_id', 'id');
    }

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
}
